version: '3.7'


x-logging:
  &default_logging
  driver: "json-file"
  options:
    max-size: "10m"


# Simple Network Management Protocol 消息通过UDP端口161接收，只有Trap信息用UDP端口162
services:
  alert:
    container_name: snmp_trap_alert
    build:
       context: .
       dockerfile: ./Dockerfile
    image: snmp_collector:2.0.0
    ports:
      - "162:162/udp"
    environment:
      SNMP_PORT: 162
    volumes:
      - .:/app
      - ./mibs/:/root/.pysnmp/mibs/
    entrypoint: sh -c 'if [ -n "$ENTRYPOINT" ]; then echo "exec $ENTRYPOINT"; exec $ENTRYPOINT; else exec /app/bin/snmp.sh; fi'
    restart: "${RESTART_POLICY}"
    logging: *default_logging

  server:
    container_name: snmp_server
    build:
       context: .
       dockerfile: ./Dockerfile
    image: snmp_collector:2.0.0
    ports:
      - "162:162/udp"
    environment:
      SNMP_PORT: 161
    volumes:
      - .:/app
      - ./mibs/:/root/.pysnmp/mibs/
    entrypoint: sh -c 'if [ -n "$ENTRYPOINT" ]; then echo "exec $ENTRYPOINT"; exec $ENTRYPOINT; else exec /app/bin/snmp.sh; fi'
    restart: "${RESTART_POLICY}"
    logging: *default_logging
